### ISSUE TITLE
Not able to connect to remote via ssh

### ISSUE THREAD

**Issue by sveinugu** [tillberg/gut#11]
I am not able to understand what goes wrong here. Is there some bug in the code?

Syncing from a mac to a linux (RedHat 6) host, using SSH key pair authentication.

`MyMac:~ sveinugu$gut sync -v ~/somedir myhost.com:~/somedir`
`2016-03-03T13:30:23Z [localhost] $ uname (71409) -> 0`
`2016-03-03T13:30:23Z [localhost] $ env (71410) -> 0`
`2016-03-03T13:30:23Z [localhost] $ stat -f %HT,%Xp,%z,%m /Users/sveinugu/.guts/gut-build/bin/gut (71411) exit status 1`
`2016-03-03T13:30:23Z [localhost] $ git version (71412) -> 0`
`2016-03-03T13:30:23Z [localhost] $ autoconf --version (71413) -> 0`
`2016-03-03T13:30:23Z [localhost] $ make --version (71435) -> 0`
`2016-03-03T13:30:23Z [localhost] $ gcc --version (71436) -> 0`
`2016-03-03T13:30:23Z [localhost] $ ls -A /Users/sveinugu/.guts/pidfiles (71439) -> 0`
`2016-03-03T13:30:23Z [localhost] $ cd /Users/sveinugu/somedir && pwd -P (71440) -> 0`
`2016-03-03T13:30:23Z [localhost] $ mkdir -p /Users/sveinugu/.guts/pidfiles (71441) -> 0`
`2016-03-03T13:30:23Z [localhost] $ cd /Users/sveinugu/somedir && pwd -P (71442) -> 0`
`2016-03-03T13:30:23Z [localhost] $ dd of=/Users/sveinugu/.guts/pidfiles/gut-_Users_sveinugu_somedir.pid (71443) -> 0`
`Failed to connect to myhost.com: Timed out waiting for PID`
`Stopping all subprocesses...`
`2016-03-03T13:30:26Z [localhost] $ ls -A /Users/sveinugu/.guts/pidfiles (71447) -> 0`
`2016-03-03T13:30:26Z [localhost] $ cd /Users/sveinugu/somedir && pwd -P (71448) -> 0`
`[insilico.hpc.uio.no] Timed out in KillAllSessions while waiting for processes to exit.`
`2016-03-03T13:30:26Z [myhost.com] $ uname (-1) | 2016-03-03T13:30:26Z [myhost.com] $ env -0 | 2016-03-03T13:30:28Z [myhost.com] $ ls -A .guts/pidfiles
 | Exiting.`

**Comment by thdxr** [comment]
I am also seeing this

**Comment by tillberg** [comment]
I'm kind of afraid that the bug here is that the kind of wonky shell hacking that I implemented here -- https://github.com/tillberg/bismuth/blob/9046541b81f3ba206003e232a8b3fd5cd014ed3a/session.go#L35-L39 -- is not working right. (bismuth is used by gut for running various gut-commands in sub-processes)

In that code, I echo the process ID of the shell session process to stderr, then use exec to replace that process with the desired command. And then after the process exits, it writes a special string followed by the exit code. This all gets filtered out of stderr by https://github.com/tillberg/bismuth/blob/master/filtered_writer.go.

And that's kind of insane and brittle and maybe something about the shell invoked on the remote host behaves differently? :/

**Comment by sveinugu** [comment]
Are you looking at replacing this hack with something cleaner? Gut really seems to fit with our development setup, if only it would work! :-)

**Comment by tillberg** [comment]
Alas, I haven't been able recently to invest much development time into gut. I'm glad you like the concept, though!

I've actually switched myself over to using syncthing for bidirectional synchronization between my workstations, https://github.com/tillberg/nsync for unidirectional continuous synchronization (I haven't written any documentation for that yet, alas), and gut-sync for version tracking/history on each node (e.g. `gut sync ~/work` -- it just commits changes continuously, but doesn't sync across hosts).

But, that all said... I've reproduced this issue now and I think I might be able to fix this soon.

**Comment by tillberg** [comment]
I fixed a rather glaring bug in my https://github.com/tillberg/bismuth library. I had gotten interrupted in the middle of a major refactor last summer, and had avoiding "releasing" a new version of gut yet. So binary versions of gut (i.e. via that ridiculous curlbash in the README) would work (for some/many folks, anyway). Buuut... for source installations of gut, it was broken because I was pushing unfinished code to bismuth's master. I'm sorry about that!

I've updated https://github.com/tillberg/bismuth to fix this issue. I think that you should be able to do `go get -u github.com/tillberg/gut` (or just `go get -u github.com/tillberg/bismuth`) and things might work better.

**Comment by sveinugu** [comment]
Thanks for the bugfix! I have now made it run (after struggling with some compiling issues which were due to my local setup). It worked flawlessly for local autocommitting, which is a very nice feature in itself. 

I does however not sync files correctly for me towards a remote. I did not see any error messages, unfortunately. The gut remotes are set to "remote.origin.url=gut://localhost:34130/wtndujhi_Users_sveinugu_testing_aaaaa/" for both synced directories, which seems strange to me, but might be the way it works. 

Based upon your comments, however, I think I will try out syncthing instead, especially since you are using that solution yourself..

Thanks for the support!

**Comment by tillberg** [comment]
Great, thanks for trying it out! For posterity, at least -- that remote.origin.url looks OK; gut sets up SSH tunnels for each of the remote git-daemons. `localhost:34130` is the local end of the tunnel, and the other host's gut-daemon would (when it works right) be listening on the other end of the tunnel.
